### ISSUE TITLE
Removed climb / historical description tag

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#1244]
Not sure if there is already a way to flag this? Was thinking of a new tag 'No longer possible'. Could be used for banned routes, routes that no longer exist etc. I don't think we need finer grained tags for each case. It could also re-use or inherit from the Legality > Closed / Illegal area tag.

Would render something like this:

![image](https://f.cloud.github.com/assets/187449/1250469/b99eb70a-2af9-11e3-8d40-cb2af5f4e8e3.png)

Also because of the way the tags are separate to the node editing process, it's quite hidden to edit a route's tag from list view. We really should merge the tags into the bulk edit #826 as part of this and the other new tag work for Nicky #1241

**Comment by lordyavin** [comment]
@brendanheywood Thanks for pointing me to this issue. I did a search before raising #1950 but for some reason I didn't find.

So, any schedule changes for this feature?

**Comment by scd** [comment]
not on my radar right now

**Comment by brendanheywood** [comment]
I just had a random thought for a quick workaround: just copy this Unicode char into the title: 🚫

A little hacky but should look ok and give use something to search on to find if we do implement it properly. 

Please give it a go @lordyavin and paste the URL of the example into this issue

**Comment by lordyavin** [comment]
Oops. I did something wrong. Now the route I added the Unicode char can't be edited anymore and the sign isn't displayed.

>Cannot continue process: could not get cache record for node '249626985'
>State: 18544
>Error Code: 2
>CodeReference: CIDS::Process::SupplyInformation::BulkEdit, /opt/CIDS/perllib/CIDS/Process/SupplyInformation/BulkEdit.pm, 677 

Modified the route 'Lauf der Dinge' in this area: http://www.thecrag.com/climbing/germany/schwaebische-alb/area/249625830

**Comment by scd** [comment]
bug in code which failed if route had blank name. Normally route should not have blank name but I am guessing another bug has allowed this. I have restored the route

**Comment by scd** [comment]
It turns out there were four issues here. Three were easy to fix but the core issue is a significant piece of work. It turns out that our MYSQL utf collation set uses 3 byte collation not the full 4 byte. This means that some unicode charaters will not be accepted. Doh.

There is a different utf8 collation set we can use which will fix the issue - utf8mb4 but a major piece of work to upgrade.

https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by scd** [comment]
see #1968

**Comment by scd** [comment]
@lordyavin this looks like it is going to take a fair while to fix properly. 

If you hash tag the route (in the description field) with something that you will remember then in a couple of months when the functionality is ready you can do a search for that hash tag and update the routes properly.

For example

#archive 

I know it is sub-optimal, but it means you can get the data entry out of your head for a while.

**Comment by brendanheywood** [comment]
@scd it seems adding new structured tags is pretty easy in the grand scheme of things, how about instead we implement this as a new structured tag, probably under 'Condition' and then I can do all the rest in the template to convert that to the red circle.

 'archive' isn't quite the right word, this mostly needs to cover rockfalls mostly to distinguish it from merely forbidden which we already have. Something like 'destroyed' or 'ruined'. 'Unclimbable' might suggest that it's just really hard.

**Comment by scd** [comment]
Sounds good. We can get different tags for different reasons.

**Comment by scd** [comment]
@lordyavin do you want to do a bit of thinking as to what structured tags you want and under what grouping. I think we will put them in route character. Note that they can be area and/or route tags.

This is better than the archive tag because archiving has specific functionality which would have to be turned off, which requires a fair bit of analysis.

Doing it as structured tags is now a small and manageable. I await your input.

**Comment by brendanheywood** [comment]
Well I think the 80% use case is a climb that has been damaged beyond recognition or removed like a fallen pillar. Suggested: destroyed

The next use case I'd say is a sport route while not nesesarily badly bolted (ie over a crack) has been removed for whatever reason and cannot be trad climbed. Suggested: chopped

Then I think we get into much more edge case stuff, like a route buried by mud after a flood (seen it), or flooded by daming. Note sure how much we care, these are functionary still destroyed but could conceivably come back later, and the details are best in the text or an annotation anyway.

**Comment by lordyavin** [comment]
I agree with Brendans proposals. Destroyed and chopped are good tags. But I hope that these tags are going to be reflected in the route list of a crag. Like the stop sign we tried ;-) Additionally destroyed routes should not be listed in PDF guides or the Crag Guru.

Maybe we need a new tag group like "condition".

**Comment by scd** [comment]
If Brendan is happy with the group 'Condition' we could go with that. The problem I have with the word condition is that it should have all ranges of tags including good condition. So maybe we need a group that implies only exception tags are used.

What about areas, are their similar tags (eg a cliff face collapses).

There is no rush to get all the functionality in place, but the tags is a start. As soon as we all agree on a heirachy (group and list of tags) for both routes and areas I will make the database config change. There is room for icons associated with tags, so that is just a process we have to go through.

**Comment by lordyavin** [comment]
Oh I see we already have a "condition" group as child of "route character". We should be careful not to mix it up. I understand your point about "good" conditions. I think without a "condition" tag the crag/route is implicitly climbable.

Maybe the destroyed tag fits into the access tags. If a route or a crag is destroyed it is not accessible any more.

**Comment by brendanheywood** [comment]
> Additionally destroyed routes should not be listed in PDF guides or the Crag Guru.

I think we should leave this for the time being for the PDF's, many guides include them on purpose and I think the index and the pdf's should at least be the same. Crag guru I agree should not suggest them, but I'm ok with leaving that for round 2, we need to make sure that query stays super fast for normal crags with nothing removed.

**Comment by brendanheywood** [comment]
I think since the last update we implemented the archive flag for gym routes which could be repurposed here. 

But I think another alternate and superior implementation would be that we have another type of historical event in the same vein as set / fa / ffa / maintained (see #1865) ie 'removed' - this appeals to me as it covers the whole cradle to grave life-cycle of a route using the same data model. It's better than a tag as it has an optional partial date for when the route was destroyed, and you can also put in who destroyed it (if that makes sense) and other comments. It also means we get a few things for free like sorting a list of routes by important historical date. We don't yet validate that ticks are after the FA date, but when we do the logic for validating that it is also before the removed date would be consistent too.

**Comment by lordyavin** [comment]
Hey there. Anything I can test? I'm still missing the sign in the route/area list for closed/prohibited climbs and areas.

**Comment by lordyavin** [comment]
BTW it is still not possible to use the proposed unicode character in the title. After saving the title is empty.

**Comment by scd** [comment]
yeh I know, sorry

**Comment by brendanheywood** [comment]
https://www.thecrag.com/discussion/1244807922/cohiba--cohiba-development

**Comment by brendanheywood** [comment]
+1 from support email re:

https://www.thecrag.com/climbing/australia/grampians/mt-william/area/12999151

Apparently this area is not so much 'removed' as just the fires turned it into a pile of choss. So whatever we do for removed routes could do with a softer variant for simply degraded routes. Thinking about stars and grades there is some overlap the route history issue (https://github.com/theCrag/website/issues/1865) because we might reset the stars or grade so that a once popular but now choss route doesn't show up in icons or quality searches

**Comment by brendanheywood** [comment]
* [ ] https://www.thecrag.com/climbing/australia/mountain-quarry/area/12141613#n2561209239

**Comment by rouletout** [comment]
Currently we use "closed" for this along with a description why which seems to work fine, closing
