### ISSUE TITLE
In between slash grades

### ISSUE THREAD

**Issue by birgander2** [theCrag/website#1951]
Would it be possible to enable slash grades for the UIAA system? I don't like them neither, but they're common practice in almost every topo I know. I mean grades like for example 7/7+, denoting a grade in between 7 and 7+. This is not the same as thecrag-style '7 to 7+', which mean the entire range from 7 until 7+, if I understood correctly.

**Comment by scd** [comment]
Hmmm, slash grades have been a real pain, because it can mean one of three things:
  * I cannot f*%^ing decide
  * Somewhere in the grade range depending on how you do it
  * Precisely in-between the two grades and in some systems they have become a grade in their own right (this makes it even more confusing if you then have inbetween grades for inbetween grades).

The reality is that no grade is exact but rather a subjective approximation made by the route setter and the community. Weather conditions, climbers height, etc can all effect how hard the actual climb is for a particular person.

Internally we treat all grades as ranges, even single grades have an inherit range. 

I am wondering if we should just display all grade ranges with consecutive grades as 7/7+ rather than '7 to 7+'. Actually I thought I had done this, or maybe just planed to do it.

**Comment by brendanheywood** [comment]
If we assume for the minute that all UIAA slash grades always mean a distinct grade and never a grade range (thecrag style) , what does this mean technically for us to implement it? If we add a flag for each grade system called say 'has-slashes' and only UIAA has this set, would this be enough? This would by necessity disable any concept of inbetween grades when parsing for that system.

Also would it be fair to say that 7/7+ is not actually 'between' grade between 7 and 7+, but more like a grade range which covers from half way through 7 to half way through 7+ instead? So the creation of 7/7+ will not affect any of the existing grade definitions at all. @birgander2 what's your thoughts on that?

If that is the case then the different parsing logic could be as simple as 'a slash means a union of multiple grades' vs 'a slash means a mean of the grade boundaries'

**Comment by birgander2** [comment]
Yes, '7/7+' would be a grade from half way the range of 7 to half way the range of 7+, while '7 to 7+' would be the sum of both ranges. In this way one could distinguish both situations.

I agree that slash grades are a pain, but unluckily they are reality. In my experience (UIAA) in 90% of the cases they mean 'in between', but certainly there are exceptions. I think, however, that it is better to leave this decision to the user/editor and not to the system. More precisely, it would be great to have both option on thecrag.

**Comment by scd** [comment]
We will need to set a flag for the intepretation of the inbetween grade or grade range. This is a simple UI - if the parsing input uses a slash then the flag is set.

Applies to all grading systems.

I will default all existing consecutive grade ranges to an in-between grade because that is how it is mostly being interpreted.

**Comment by scd** [comment]
The statistical performance analysis from CPR is telling us that it does not matter so we should just dislay as a slash grade all the time.

**Comment by birgander2** [comment]
I'm really waiting for slash grades to be supported. The problem is that as long as they're not, few people will enter them, though they're the given grade. Currently, "7/7+" is displayed as 7+, and "7 to 7+" selects the lower grade during ticking. Both is not appropriate for in-between grades. What do you mean, that both "7 to 7+" and "7/7+" is interpreted the same way? Yes, why not. But it would be necessary, that the climber can select a slash grade when ticking.

**Comment by lordyavin** [comment]
Damn it. Some of my last additions used the slash but I added them with 'to'.

**Comment by scd** [comment]
No I think that we will end up showing all adjacent grades which are next to each other as a slash grade because from a performance perspective they are effectively the same and it seems as though the slash is the more common use case

**Comment by quaestor** [comment]
There seems to be something wrong with the parsing of slash grades; 9+/10- is parsed to 9+/11-:

<img width="108" alt="screenshot 2018-04-26 13 53 00" src="https://user-images.githubusercontent.com/54371/39304262-6c81e874-4959-11e8-93b1-c996b8bcf082.png">

**Comment by scd** [comment]
This is a display issue, which is fixed in dev

**Comment by lordyavin** [comment]
Still not released, right? Found another issue 
![grafik](https://user-images.githubusercontent.com/1528540/39700309-ffe9377e-51fc-11e8-9bce-02a0f23a886c.png)
see https://www.thecrag.com/climbing/spain/margalef/route/26386941

**Comment by lordyavin** [comment]
Still not done?

**Comment by killakalle** [comment]
I've just create a boulder route with a grade of 5+/6A type: boulder, grading system: French

The displayed grade icon is reverse: 6A 5+
See a screenshot.
![image](https://user-images.githubusercontent.com/30682796/76026046-56588e80-5f2e-11ea-840d-170aba1974fc.png)

This is the route:
https://www.thecrag.com/climbing/spain/montesa/route/3126428304

The in between grade is probably given by the route setters:
https://elev-arte.com/images/escuelas_escalada/COMVALENCIA/VALENCIA/montesa/bloqueMontesa08.jpg

Seems related to the issue you're discussing here.

**Comment by Mdemaillard** [comment]
The last 3 linked examples of display issues are sorted.
I tested, the "ranges" (17 - 19) (17 to 19)(17 / 19) are parsed as rang and displayed 17-19 
the "adjacent ranges" (17-18) (17 to 18) (17 / 18) are parsed and displayed as 17/18
work as well in other grading systems like french
Closing, please reopen if i missed any open todo
