### ISSUE TITLE
Critical login failure via link on facebook

### ISSUE THREAD

**Issue by brendanheywood** [theCrag/website#2312]
Tonight I was on facebook on my phone and read this, and just tried to open it and read it and had a complete shit of a time for about 10 minutes without success:

![image](https://cloud.githubusercontent.com/assets/187449/17462580/ff514e86-5cf4-11e6-8bff-86d81b1f7c15.png)

* [ ] Bug # 1: I clicked on it, it's a public discussion and should have just opened inside facebooks embedded browser but instead I got redirected to the login page which I thought was a bit odd

* [ ] Bug # 2: So I thought that's weird but I'd just work around it - I open the link in safari, where I know I am already logged in so it should just work, but nope I got the login page again. So I logged in via google, and clicked on the link again, and nope got the login link again.

Then I realized I wasn't actually requesting the discussion page, but instead the login url with the LoginTarget set to the discussion page:

https://www.thecrag.com/CIDS/cgi-bin/cids.cgi?return=%2Fdiscussion%2F955313226%2Fmt-tibrogargan--salmon-traverse-bolted;D%3ALoginTarget=%2Fdiscussion%2F955313226%2Fmt-tibrogargan--salmon-traverse-bolted;C%3AState=13216;C%3AHideNavigation=1

and not this:

http://www.thecrag.com/discussion/955313226/mt-tibrogargan--salmon-traverse-bolted

I tried this via a bunch of ways, ie if was already at the login page in the embedded browser, and then click 'open in safari' from there I would expect to be taken to the loginpage url but it should just immediately log me in and then redirect back to the discussion page. But it didn't - we should fix this so the login process page immediately passes if you already have a valid session. I have also separately just confirmed this bug in chrome on my dev box too. I can double confirm this on my phone because if I click on the logo on the login page then I go straight to my dashboard.

I also tried long pressing on the raw url in the facebook post, copying the url, and manually opening it in safari but still got the same result. The url I end up pasting is the login page one already. So I think internally when facebook goes off and grabs the url to do it's opengraph preview, it is being incorrectly served a redirect to the login url which is being cached incorrectly even though it's a non cacheable http status.

So through a combination of multiple bugs between facebook and us it's impossible to directly access this page!

* [ ] Bug # 3: In hindsight if I go back to facebook and look at the preview I can confirm it is screwed up, it's showing a generic preview instead of something specific to that discussion page. When I debug this in facebook's tools this is the raw source of what FB see's which is totally wrong:

https://developers.facebook.com/tools/debug/echo/?q=http%3A%2F%2Fwww.thecrag.com%2Fdiscussion%2F955313226%2Fmt-tibrogargan--salmon-traverse-bolted

At first I suspected this may have been a side effect of our FB app id not having the api verison upgraded. Even thought this is unrelated FB may have been doing something dumb, but that raw echo above is before they even parse the page so don't even know what app id it is yet. Also the Open graph page says it is getting back a http 206 instead of 200 which is also weird.

https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fwww.thecrag.com%2Fdiscussion%2F955313226%2Fmt-tibrogargan--salmon-traverse-bolted

**Comment by scd** [comment]
We have set the discussion page to force login. In hindsight this is a crazy setting and I don't know what we were thinking - probably wanting people to create an account.

I have changed the flag and fixed in production. I think that Facebook is storing the login link, possibly because the forced login in the first place. 

On a side note, when I looked into the Facebook app upgrade it looked like we did not have to do anything. Their report said we were not using any api calls that needed upgrading.

**Comment by brendanheywood** [comment]
I still think it's fairly important to also fix the login process to jump straight in if you are already authenticated. eg that link above still fails

**Comment by scd** [comment]
sure I will put it on the list.

**Comment by scd** [comment]
I have updated login process to jump straight to the login target page if one is set and you have a valid session.

**Comment by brendanheywood** [comment]
Awesome, tested and works

**Comment by scd** [comment]
I cannot believe that some of these serious deficiencies can hang on for so long. This would also explain why google is not getting our discussions

**Comment by brendanheywood** [comment]
I just did a test crawl via google which is working:

https://www.google.com/webmasters/tools/googlebot-fetch-details?hl=en&authuser=0&siteUrl=http://www.thecrag.com/&path=discussion/955313226/mt-tibrogargan--salmon-traverse-bolted&timestamp=1470616016217

Although it isn't loading the avatars because they are blocked in robots.txt so the preview is slightly broken. What was the rational originally for blocking them? Just cpu / robot load?

**Comment by brendanheywood** [comment]
> I have updated login process to jump straight to the login target page if one is set and you have a valid session.

Does that mean if a target isn't set, but you do have a session, then it won't just jump to the dashboard?

**Comment by scd** [comment]
> What was the rational originally for blocking them? Just cpu / robot load

Cannot remember. I think we should re-address and allow them. I have made the change on prod. Could you please retest.

> Does that mean if a target isn't set, but you do have a session, then it won't just jump to the dashboard?

That process is fine. Please test though. There is duplicate code for login. It needs a massive refactor but is tied to the fact that process code use cgi-bin and templates use mod apache, which is totally shit.

**Comment by brendanheywood** [comment]
avatars all work in preview now :)
