### ISSUE TITLE
Error message when trying to "Update Photo"

### ISSUE THREAD

**Issue by pmonks** [theCrag/website#2405]
### Steps to reproduce:
1. Navigate to a photo uploaded by yourself
2. In `Photo Record`, click `[edit]`
3. Down the bottom, click the `Update Photo` button

### Expected result:
Presented with edit form for the metadata of the image (Title, Climber, Photographer, Date, Description).

### Actual result:
Following error appears, with `Return to start of process` button:
```
Cannot continue process: could not find photo dimensions

State:

Error Code: 2

CodeReference: CIDS::Process::SupplyInformation::ReviewPhoto, /opt/CIDS/perllib/CIDS/Process/SupplyInformation/ReviewPhoto.pm, 1313
```

**Comment by scd** [comment]
@pmonks I think I have fixed this. Please test.

Please close the issue if it works.

**Comment by pmonks** [comment]
👍 LGTM!

**Comment by Drazhar** [comment]
For me this isn't fixed. When I try to edit a photo and press save, I get the following error:

Cannot continue process: mandatory field 'PhotoOriginalWidth' missing in record 'Photo'

State: 15712

Error Code: 2

CodeReference: CIDS::Process::SupplyInformation::ReviewPhoto, /opt/CIDS/perllib/CIDS/Process/SupplyInformation/ReviewPhoto.pm, 1464

**Comment by brendanheywood** [comment]
Maybe this depends on the particular image / metadata, can you provide a link to the image involved please?

**Comment by Drazhar** [comment]
I wanted to remove the title of: https://www.thecrag.com/photo/990921516

**Comment by scd** [comment]
@Drazhar try again now.

There were a couple of additional references. The root cause of this is hunting down all the error tests for a retired photo field. We will get there :)

Please closed if fixed for you

**Comment by Drazhar** [comment]
Now it works, nice!

**Comment by Drazhar** [comment]
close

**Comment by Drazhar** [comment]
close #2405

**Comment by Drazhar** [comment]
Fixes #2405

**Comment by Drazhar** [comment]
close #2405
