### ISSUE TITLE
WebCover false Rotation

### ISSUE THREAD

**Issue by nicHoch** [theCrag/website#2879]
**What happened?**
Defined a WebCover for:

https://www.thecrag.com/climbing/switzerland/alpen/zentralschweiz/area/410684505

with image:
https://www.thecrag.com/photo/411250605

Rotation of WebCover and Image do not align.

**What you expected:**

Rotation of WebCover and Image should align.

**Comment by brendanheywood** [comment]
Pretty sure this is already fixed and not yet released as part of https://github.com/theCrag/website/issues/2303#issuecomment-315592963

**Comment by scd** [comment]
I also think that this has been fixed in dev. I have tagged as release followup for us to check

**Comment by scd** [comment]
Hmmm, still broken. I am going to leave this as an open bug.

**Comment by brendanheywood** [comment]
@scd just found a few in my dev box when testing home page stuff, not sure it is this issue or this issue https://github.com/theCrag/website/issues/2303

https://brendan.thecrag.com/climbing/australia/bungonia-gorge/webcovers

https://brendan.thecrag.com/climbing/australia/bungonia-gorge/area/11771461

https://brendan.thecrag.com/climbing/austria/area/518688360/webcovers

https://brendan.thecrag.com/climbing/austria/area/518688876

These are all ok in prod,

**Comment by scd** [comment]
This is a logic issue with our url. The web cover image is

https://image.thecrag.com/0x1726:3786x2988/fit-in/1200x400/filters:rotate(90)/ce/5e/ce5e6b85259f24febaacb5ef1cf83532054527c8

The rotate happens after fit-in.

**Comment by scd** [comment]
Manually constucting a roughly equivalent url we should get something like this:

https://image.thecrag.com/1000x0:2262x3786/fit-in/400x1200/filters:rotate(90)/ce/5e/ce5e6b85259f24febaacb5ef1cf83532054527c8

**Comment by scd** [comment]
This was a bit of a mindfuck but is fixed now. All the thumbor operations are pre rotate, but the focus window is post rotate. So if there is a rotate the algorithm has to transpose the focus window back to the pre rotate. We now get the following url generated:

https://image.thecrag.com/1236x0:2498x3786/fit-in/400x1200/filters:rotate(90)/ce/5e/ce5e6b85259f24febaacb5ef1cf83532054527c8

Which matches the prod image generated from the following url:

https://static.thecrag.com/img/0x1726:3786x2988/fit-in/1200x400/ce/5e/ce5e6b85259f24febaacb5ef1cf83532054527c8

Note that this issue exists in prod, but is an edge case we would not see much because when thumbor honors exif there are very few photos with a rotate in the url.

**Comment by scd** [comment]
This issue is fixed techincally on dev. However after release there is a followup issue as the focus is in the wrong spot.

**Comment by brendanheywood** [comment]
I've confirmed this is all good on brendan. I'm not sure if this was related to the first issue Nicky raised here, but either way I've also retested it and it all looks good so closing this

https://brendan.thecrag.com/climbing/switzerland/alpen/zentralschweiz/uri/area/410684505

https://brendan.thecrag.com/climbing/switzerland/alpen/zentralschweiz/uri/area/410684505/webcovers/

https://brendan.thecrag.com/photo/411250605
