### ISSUE TITLE
Remove "Leave Site" Warning 

### ISSUE THREAD

**Issue by rouletout** [theCrag/website#2982]
**What happened?**

In cases where you select a route from the route list using the checkbox to e.g. edit it or log an ascent the pop-up "Do you want to leave this site?...." appears before continuing. Most of the time this is not useful and an unnecessary interaction.

(please also provide urls and screen shots)

**What you expected:**
<img width="1027" alt="screen shot 2017-12-15 at 09 00 57" src="https://user-images.githubusercontent.com/19162952/34047913-78210358-e177-11e7-93e6-5830c00e57f0.png">

No pop-up at all.
(please also provide urls and screen shots)

**Comment by brendanheywood** [comment]
Can you please reproduce it with a screen shot in english and also try it in a few browsers and see if it's just one or all? Also let me know the versions etc. I will probably have to do a debug screen share with you

**Comment by rouletout** [comment]
Here you go, my Firefox is German and version 57.0.1 (64-Bit), my Chrome Version 63.0.3239.84 (Official Build) (64-bit) - both react the same way. On my iPhone the pop up is not appearing.

<img width="1310" alt="screen shot 2017-12-16 at 09 16 44" src="https://user-images.githubusercontent.com/19162952/34071803-ff4c94bc-e241-11e7-8747-46f6885b403e.png">

**Comment by brendanheywood** [comment]
Yeah I'm probably gonna need to live debug this with you, this works fine for me in prod and on my dev box.

Can you try doing a cache clear / full reload and test is here:

https://brendan.thecrag.com/climbing/australia/ebor-gorge/area/12094681

If it correctly isn't warning when trying to tick, can you also test it correct IS warning if you try to leave th tick page after entering text?

**Comment by rouletout** [comment]
Same thing (see attached); also, the menu on the right of the route looks really weird when you are not logged in (see second screenshot).

<img width="977" alt="screen shot 2017-12-17 at 09 06 46" src="https://user-images.githubusercontent.com/19162952/34080840-f0abfd8a-e309-11e7-96c0-c2eb984ebb7b.png">
<img width="885" alt="screen shot 2017-12-17 at 09 07 16" src="https://user-images.githubusercontent.com/19162952/34080848-fa703c1e-e309-11e7-90d0-a9ab62971f65.png">

**Comment by brendanheywood** [comment]
@rouletout is this still happening?

**Comment by rouletout** [comment]
Yes if I use the right button (Edit), not if I click the bottom "Log Ascents"

**Comment by lordyavin** [comment]
Getting this if starting a discussion too:

![grafik](https://user-images.githubusercontent.com/1528540/37525093-13f48c04-292c-11e8-9b79-0e1e50463b4d.png)

**Comment by brendanheywood** [comment]
Ok I have tracked down both of thesem @lordyavin / @rouletout can you please also retest

https://brendan.thecrag.com/climbing/australia/ebor-gorge/area/12094681

https://brendan.thecrag.com/climbing/australia/ebor-gorge/area/12094681/forum

**Comment by rouletout** [comment]
Still the same on both, Chrome and Firefox - using the button below, the pop-up is not displayed, using the right Edit>Log Ascents it appears.

**Comment by brendanheywood** [comment]
I could reproduce but now can't, can you please do a full cache clear and try again. I am pretty sure this is fixed

**Comment by rouletout** [comment]
Cleared all time cache and all other stuff you can clear in Chrome, re-started it, still the same....

**Comment by scd** [comment]
Are you on brendan.thecrag.com?

**Comment by lordyavin** [comment]
For me fixed on brendans version. (Firefox)

**Comment by brendanheywood** [comment]
Ok can everyone please test again, and test a bunch different things:

1) route selection using the checkbox
2) route selection clicking anywhere on the route
3) route editing, logging

Also confirm that places that should still have the save exit warning still do, like most process pages
