### ISSUE TITLE
Most climbed area missing from profile page

### ISSUE THREAD

**Issue by Dturf** [theCrag/website#3493]
As of the last few days Frog Buttress has dissapeared from my profile page where it displays your 5 areas/crags which have the most ascents. Mine now ony shows my top 4, despite most of my ascents being at Frog.

Profile URL:

https://www.thecrag.com/climber/dturf1

**Comment by lordyavin** [comment]
The sorting of favorite crags is a thing that bothers me too.

**Comment by brendanheywood** [comment]
@lordyavin can you please open a new issue and flesh that out with what you would prefer to see

@Dturf that is super weird, nothing obvious, more digging required

**Comment by proceedhhx** [comment]
@brendanheywood 
Maybe it's the same issue that causes some problems with the Kalymnos (and it's partent) node.

[My profile](https://www.thecrag.com/climber/tobiau) says 145 ascents for "Aegean Islands" (Partent of Kalymnos), but after clicking on the number "145" it lists 155 ascents for Kalymnos. [link](https://www.thecrag.com/ascents/by/1118084781/in-setting/natural/at/1665159444). For other areas the numbers match.

I think for Kalymnos this first happend after a bigger user update related to area types - the by area chart shouldn't show "aegean islands" in the first place but started to do that at that point.

Another ([better example](https://www.thecrag.com/climber/martinkosir)) that something is wrong.

**Comment by scd** [comment]
This looks like a denormalisation field is a little bit out of sync. I am running the `./fix-node-collector` script in my dev to see if it fixes the issue.

**Comment by scd** [comment]
See also https://github.com/theCrag/website/issues/3357

**Comment by scd** [comment]
Fixed in prod

**Comment by brendanheywood** [comment]
I'm re-opening this, it's clearly not fixed (yet?). The original issue is not showing Frog buttress (with 382 ascents) as the top crag in Notable ascents by area:

https://www.thecrag.com/climbing/australia/frog-buttress/ascents/by/dturf1/

https://www.thecrag.com/climber/dturf1#notable

**Comment by Dturf** [comment]
Thanks for re-opening Brendan. Still no dice.

**Comment by scd** [comment]
I think this might be because the algorithm uses distinct routes:

https://www.thecrag.com/climbing/australia/frog-buttress/ascents/has/distinctroute/by/dturf1/?sortby=when-climbed,desc

Only 176. 

I have not confirmed this in code but it is highly likely to be the case. In which case it is not a bug but a business rule. Happy to discuss the business rule.

**Comment by brendanheywood** [comment]
The 'By area' table shows the total number of ascents and is ranked by them and links to each facet, which isn't distinct. So if it is distinct under the hood then that's quite misleading and I think the business rule is wrong. If it is tangled up in the stats from other things like the grade graphs then they should be decoupled.

**Comment by scd** [comment]
Let's just document that the business rule has changed and the implementation now should align with the new business rule. At least now we know what is the likely issue. I am not sure how much work this is.

**Comment by scd** [comment]
OK, I have reviewed the code and it does not seem to be unique ascents. This is looking like a bug not business rule issue. Sorry for the false start.

**Comment by scd** [comment]
This is really painful because it is fine in my dev. I have just spent an hour on this and cannot see any reason why this is happening. 

It looks like the hardest routes for Frog are not making it through to the template data. 

I need to find a broken example in dev before I can go any further on this. No more work on this for a while.

**Comment by Dturf** [comment]
I can 100% confirm that this happened in whatever release occurred during early July/very late June 2019. Because Frog disapeared off that table overnight.

@scd from a lay person's point of view is there anything I can do to help find a broken example? Or anything I can do to help?

**Comment by scd** [comment]
I would probably find this really quickly in my dev if it was failing in dev. 12 months ago I would have just synced a copy to my dev, but we now have growing pains and the db is too big to do this now without some infrastructure work. 

If you know of anybody else or any other examples then posting it here will help if I find there is a matching problem in dev.

I am probably also showing my frustration because I just do not get enough time to do everything we want to do on the site.

You are already doing the best thing you can to support us by being a financial supporter.

**Comment by brendanheywood** [comment]
@Dturf I've fixed this and this is hot fixed:

![image](https://user-images.githubusercontent.com/187449/65694199-cd087a80-e0b8-11e9-94a1-89f7c8e654b0.png)
