### ISSUE TITLE
"Warnings" issue in stream

### ISSUE THREAD

**Issue by proceedhhx** [theCrag/website#3522]
I issued a warning and the stream event for it has a lot of empty space.

[screen](https://www.dropbox.com/s/zq7y11q9detvrvr/warning%20issue.JPG?dl=0)
Firefox, win7

I noticed that this happens on my dashboard but not in the stream of the crag itself.

**Comment by brendanheywood** [comment]
note to self: This is a forum head css float bug interacting with the right side aside column

**Comment by scd** [comment]
I think this is fixed now

**Comment by brendanheywood** [comment]
Still an issue:

![image](https://user-images.githubusercontent.com/187449/65831254-0cbea480-e2fb-11e9-98c2-369505c96147.png)

**Comment by brendanheywood** [comment]
Reproduced and fixed in dev

![image](https://user-images.githubusercontent.com/187449/65832399-4812a080-e306-11e9-93dd-cf0b0469c4bf.png)

**Comment by scd** [comment]
The fix is not so simple. @brendanheywood your fix has caused a display regression. This is what my stream events now look like.

<img width="653" alt="Screen Shot 2019-09-30 at 8 40 13 am" src="https://user-images.githubusercontent.com/373058/65840603-5e4c4b00-e35e-11e9-9bcb-871d89bae35c.png">

**Comment by brendanheywood** [comment]
This css I changed was specific to forums, not stream events, it just happened to be wrapped inside a stream event. I think what you are seeing is a different bug as I can't see anything forum related in that screenshot, unless there is more context that has been cropped out. I've tried to replicate this using the same node and actions as yours and I can't replicate this. Can you please try and replicate this on my box?

If I was approaching this from scratch, to me that screenshot looks like an unmatched div somewhere.

**Comment by scd** [comment]
I think it is related to the fix you made. If you removed the float left
then I did something similar a while ago and it caused these side effects,
so I did not make the change as it was way more complex then I could deal
with at the time. I went looking for this to see if it was properly fixed.

**Comment by brendanheywood** [comment]
Either way I cannot reproduce it, I need to see it failing

**Comment by scd** [comment]
WTF, I cannot seem to reproduce it either. It is happening only on my dev and only on some embedded streams. It looks like some weird caching. I don't have time or energy to look into it anymore and given it works on brendan server I am happy to just close the issue.
