### ISSUE TITLE
New log type ascent does not finish loading on idle tab

### ISSUE THREAD

**Issue by killakalle** [theCrag/website#4068]
I'm not a 100% sure about the steps to reproduce, but that's my best guess.

**To reproduce**
1. Open a crag with a route list
2. Get sidetracked and do something else for 15(?) minutes
3. Remember the still open theCrag tab and return
4. Select a few routes and click "New log ascent"
5. Wait for log ascent screen to finish loading (it never finishes)
6. Click cancel
7. ....still loading...

![image](https://user-images.githubusercontent.com/30682796/169716199-902420af-cdd7-4e7c-a135-d80500796c79.png)

![image](https://user-images.githubusercontent.com/30682796/169716172-125aa02c-acfe-489f-85a2-a0a46c84a6a5.png)

**Expected**

- [ ] Can log ascents regardless of how long tab has been idle

**Comment by lordyavin** [comment]
I experience never ending loading too. A refresh F5 of the page resolves it but that should not be necessary.

**Comment by killakalle** [comment]
![Screenshot_20220605_165933_org mozilla fenix](https://user-images.githubusercontent.com/30682796/172057880-f0515ddb-e4ee-46e8-8513-e657703ac152.jpg)

This happened to me while using the new tick interface on mobile. It got stuck on loading (always showing the name of the first route) and I clicked Save several times to see if it would react.

Apparently in the background it was switching to the next route in the queue but not updating the FE. You can tell that the FE was somehow stuck because the same ascent comment was saved for each route.

**Comment by scd** [comment]
This has been addressed

**Comment by killakalle** [comment]
@scd 
I still encounter this problem.

Form does not finish loading - eventually, a reload button appears.
![image](https://user-images.githubusercontent.com/30682796/177058488-9a46cb3d-1a5b-4bc1-b7c9-17033e0af781.png)

After clicking the reload button, the only thing I notice is that the button disappears. However, the form does not load
![image](https://user-images.githubusercontent.com/30682796/177058538-0313dd54-8024-4bda-89d5-cb2c9b5d1951.png)

**Comment by scd** [comment]
I have fixed the control and transparency around loading. If you press reload does it work?

Fixing our sites scaling issues is way more complex.

**Comment by killakalle** [comment]
> If you press reload does it work?

No. After clicking the reload button, the only thing I notice is that the Reload button disappears. However, the form does not load.

**Comment by scd** [comment]
I just went through the procedure to test this and it worked for me. Can you confirm if you can do the same thing.

1. Go to the page where you are logging an ascent
2. Disconnect from the Internet
3. Log the ascent and wait for the Reload button.
4. Connect to the Internet
5. Press Reload

First I want to see if there is something about your set up that is systemically not working.

**Comment by killakalle** [comment]
@scd 
I can follow the steps above and log an ascent successfully. However, this scenario is also different from when I encounter the problem.

I encounter the problem when I keep a route page open for a longer time and come back to it to log an ascent.

e.g. you are at a crag climb a route and log it. Then you leave the page open on your phone while climbing the next route, then come back to the already open route page and try to log the next route.
