### ISSUE TITLE
New tick flow: Can't propose a grade if none is registered

### ISSUE THREAD

**Issue by lordyavin** [theCrag/website#4112]
I added a bunch of gym routes. All of them yet not rated officially. So I didn't register a grade but thought I can override (set) the ascent grade in the advanced fields of the new tick flow. But I can't because the UI elements are missing:
![grafik](https://user-images.githubusercontent.com/1528540/188950962-7906cbc5-c54b-489d-9269-2929749dc54a.png)

You may reproduce for here: https://www.thecrag.com/en/climbing/germany/route/6526810068

What I expect:
* [x] While ticking routes that are yet not rated, the UI shall provide input fields to set the ascent, proposed grade.

**Comment by nicHoch** [comment]
i had the same problem. where i created a unknown route outdoors where i did not set a grade because of uncertainty. 
Was not able to set a grade feedback at logging.
It will be a bit tricky to provide a good entry grade for the UI as it does not even know about the grading system so fare. 

Maybe a heuristic based on the mean grad of the sector and the dominant grading system would help.

**Comment by scd** [comment]
FYI difficulty feedback is about providing feedback on an assigned grade. It cannot be assigned to nothing.

GrAId is designed to work off no input grades. So for a gym with not grades, as long as the routes are ticked and hopefully number attempts filled in, we will be able to suggest grades for routes.

Why not just put a grade contribution for the route.

**Comment by lordyavin** [comment]
> Why not just put a grade contribution for the route.

It's inconvenient and what should I add as contribution if I am unsure about the grade? I don't want to update my grade contribution each time I ascended it.

The new tick UI could always contain a field to add the personal grade contribution instantly. Either a free grade selection or the grade range thing we have currently, plus a checkbox (opt in) to set this as personal grade contribution.

It's all about usability. Loading times are so bad for me, that I'm happy to switch UI as less as possible. Especially when I'm on the mobile phone.

**Comment by scd** [comment]
Just to confirm that this is gym routes you are talking about not outdoor routes.

I am really keen to get GrAId working for gym routes. It should not take many ascents before we can establish a grade. Once we have established the utility of GrAId in gyms we can then look at what else needs to be done.

**Comment by lordyavin** [comment]
No idea why GrAId is related here and the issue applies to gym and rock routes but was discovered while logging gym routes.

**Comment by nicHoch** [comment]
i also see that as an important function to get feedback of unknown/ungraded routes.
If i see a new line bolted in a sector - but do not know who put it up or what name grad is suggested. I put it in the index (mostly with a generic name) - suggesting a grade in the moment i crate the route (sometimes i have not climed it at all) would somehow give the impression that i have done the FA. I would for sure prefer to leave a grade open for the moment and collect feedback over time. But i think it is necessary to add the route already so that it can be drawn on topos/ sorted into the list ... so that the users have an entity to discuss/log on, collect information and also grade suggestions. 
I mean give feedback for existing grade is very important but also we should provide an easy way to collect initial grade suggestions for new/unrated routes.

**Comment by nicHoch** [comment]
@lordyavin we talked about that and think that a grade feedback would not be the right approach here as there is no grade to give feedback for.

the correct way would be to use the grade override.
 
so the best solution from the UX point of view would be if the grade override field is not hidden in the advanced section in case that no grade is registered.

**Comment by lordyavin** [comment]
This issue is a gym issue. I recently noticed that I can't add a grade proposal for gym routes that have registered grades.
E.g. https://www.thecrag.com/en/climbing/germany/route/6526806402

![grafik](https://user-images.githubusercontent.com/1528540/198161597-59ccc529-4206-42e4-9e70-1ffeac9d8d85.png)

**Comment by rouletout** [comment]
See also https://github.com/theCrag/website/issues/4157

**Comment by scd** [comment]
As far as I can see you can now add difficulty feedback for gym ticking. I cannot remember when we fixed this, but closing the issue now.

**Comment by lordyavin** [comment]
Is not fixed for me. Just tried to log an ascent for this route https://www.thecrag.com/climbing/test-area/area/1230605421#n8387370276 but the grade selector did not show up.

**Comment by scd** [comment]
Ahh, I think I misinterpretted this. I thought it was about difficulty feedback. You wanted to log your own grade for your gym ascent. Sorry for missing this.

**Comment by scd** [comment]
Now this should be hotfixed

**Comment by lordyavin** [comment]
Would it be a worthy enhancement to add the option of the ticked grade as grade contribution?

**Comment by killakalle** [comment]
> Would it be a worthy enhancement to add the option of the ticked grade as grade contribution?

@lordyavin 
In their current form I find the grade contributions confusing and just clutter.

- the route grade is redundant
- grAId is useful
- all the personal grade contributions should not be listed here. They should be aggregated in the grade feedback graphs on the right. And for the interested, they can look up each person's personal opinion in the ascents list.

Btw. there is a bug in the bulk import script of routes. Whenever you do a bulk import (with the help of an admin), the route grade is registered as the personal grade contribution of the submitter.

![image](https://github.com/theCrag/website/assets/30682796/070dcb99-11b9-423f-a866-55dcf03d758a)
