### ISSUE TITLE
Liechtenstein spelled wrong in User profiles

### ISSUE THREAD

**Issue by AndiAachen** [theCrag/website#4214]
For whatever Reason Liechtenstein is spelled correctly for the crags, but in the user profiles the "e" after the "i" is missing.

**Comment by AndiAachen** [comment]
https://www.thecrag.com/climber/andreasaachen

**Comment by rouletout** [comment]
<img width="676" alt="Screenshot 2023-07-20 at 07 49 45" src="https://github.com/theCrag/website/assets/19162952/b365a174-d942-4e34-8daa-1376b94369e8">

**Comment by AndiAachen** [comment]
Yes, but it should be "Li**e**chtenstein"

**Comment by scd** [comment]
I have updated our country table with the correct spelling.

The next thing to do is update our translations for key `dbconfig.country.li`

**Comment by rouletout** [comment]
done, closing

**Comment by AndiAachen** [comment]
This is not done. The issue is still the same, in my profile (and everyones profile from this country) liechtenstein is spelled worng.

**Comment by AndiAachen** [comment]
![image](https://github.com/theCrag/website/assets/139957120/bf6619bc-b9c0-4324-94d3-0f1669ede66c)

**Comment by scd** [comment]
Ahh I have now pushed the translations file. Please check again

**Comment by AndiAachen** [comment]
Now its correct, thanks!
